/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class busManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form busManagementSystem
     */
    public busManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        bus_details = new javax.swing.JButton();
        employee_details = new javax.swing.JButton();
        counter_details = new javax.swing.JButton();
        ticket_details = new javax.swing.JButton();
        trip_details = new javax.swing.JButton();
        commnt = new javax.swing.JButton();
        company_details = new javax.swing.JButton();
        emphstry = new javax.swing.JButton();
        tichstory = new javax.swing.JButton();
        mnglst = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));

        bus_details.setBackground(new java.awt.Color(204, 204, 204));
        bus_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bus_details.setForeground(new java.awt.Color(255, 51, 51));
        bus_details.setText("Bus Details");
        bus_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_detailsActionPerformed(evt);
            }
        });

        employee_details.setBackground(new java.awt.Color(204, 255, 204));
        employee_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        employee_details.setForeground(new java.awt.Color(255, 51, 51));
        employee_details.setText("Employee Details");
        employee_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_detailsActionPerformed(evt);
            }
        });

        counter_details.setBackground(new java.awt.Color(204, 255, 255));
        counter_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        counter_details.setForeground(new java.awt.Color(51, 51, 0));
        counter_details.setText("Counter Details");
        counter_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counter_detailsActionPerformed(evt);
            }
        });

        ticket_details.setBackground(new java.awt.Color(255, 204, 204));
        ticket_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ticket_details.setForeground(new java.awt.Color(255, 0, 204));
        ticket_details.setText("Ticket Details");
        ticket_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_detailsActionPerformed(evt);
            }
        });

        trip_details.setBackground(new java.awt.Color(255, 204, 102));
        trip_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        trip_details.setForeground(new java.awt.Color(0, 102, 102));
        trip_details.setText("Trip Details");
        trip_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trip_detailsActionPerformed(evt);
            }
        });

        commnt.setBackground(new java.awt.Color(255, 255, 204));
        commnt.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        commnt.setForeground(new java.awt.Color(0, 0, 102));
        commnt.setText("Comment Part");
        commnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commntActionPerformed(evt);
            }
        });

        company_details.setBackground(new java.awt.Color(204, 204, 255));
        company_details.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        company_details.setForeground(new java.awt.Color(51, 153, 0));
        company_details.setText("Company Details");
        company_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_detailsActionPerformed(evt);
            }
        });

        emphstry.setBackground(new java.awt.Color(204, 204, 255));
        emphstry.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        emphstry.setForeground(new java.awt.Color(102, 102, 0));
        emphstry.setText("Employee History");
        emphstry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emphstryActionPerformed(evt);
            }
        });

        tichstory.setBackground(new java.awt.Color(255, 153, 153));
        tichstory.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        tichstory.setForeground(new java.awt.Color(51, 0, 0));
        tichstory.setText("Ticket History");
        tichstory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tichstoryActionPerformed(evt);
            }
        });

        mnglst.setBackground(new java.awt.Color(255, 204, 255));
        mnglst.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mnglst.setForeground(new java.awt.Color(102, 102, 102));
        mnglst.setText("Manager List");
        mnglst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnglstActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ticket_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bus_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(company_details, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(employee_details, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tichstory, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(commnt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(trip_details, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(counter_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mnglst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emphstry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bus_details, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_details, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticket_details, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tichstory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnglst, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emphstry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trip_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(company_details, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(commnt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bus_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_detailsActionPerformed
        // TODO add your handling code here:
        busDetails field = new busDetails();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bus_detailsActionPerformed

    private void employee_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_detailsActionPerformed
        // TODO add your handling code here:
        Employeedetails field = new Employeedetails();
              field.setVisible(true);
               setVisible(false);
    }//GEN-LAST:event_employee_detailsActionPerformed

    private void counter_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counter_detailsActionPerformed
        // TODO add your handling code here:
        Counterdetails field = new Counterdetails();
               field.setVisible(true);
               setVisible(false);
    }//GEN-LAST:event_counter_detailsActionPerformed

    private void ticket_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_detailsActionPerformed
        // TODO add your handling code here:
        Succes field = new Succes();
               field.setVisible(true);
               setVisible(false);
    }//GEN-LAST:event_ticket_detailsActionPerformed

    private void trip_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trip_detailsActionPerformed
        // TODO add your handling code here:
        Tripdetails field = new Tripdetails();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_trip_detailsActionPerformed

    private void commntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commntActionPerformed
        // TODO add your handling code here:
        comment field = new comment();
        field.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_commntActionPerformed

    private void company_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_detailsActionPerformed
        // TODO add your handling code here:
       companyDetails field = new companyDetails();
        field.setVisible(true);
        setVisible(false); 
        
    }//GEN-LAST:event_company_detailsActionPerformed

    private void emphstryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emphstryActionPerformed
        // TODO add your handling code here:
        emphistory field = new emphistory();
        field.setVisible(true);
        setVisible(false); 
        
        
    }//GEN-LAST:event_emphstryActionPerformed

    private void tichstoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tichstoryActionPerformed
        // TODO add your handling code here:
        ticketHistory field = new ticketHistory();
        field.setVisible(true);
        setVisible(false); 
        
        
    }//GEN-LAST:event_tichstoryActionPerformed

    private void mnglstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnglstActionPerformed
        // TODO add your handling code here:
        showManager field = new showManager();
        field.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_mnglstActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frontLog field = new frontLog();
        field.setVisible(true);
        setVisible(false); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bus_details;
    private javax.swing.JButton commnt;
    private javax.swing.JButton company_details;
    private javax.swing.JButton counter_details;
    private javax.swing.JButton emphstry;
    private javax.swing.JButton employee_details;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton mnglst;
    private javax.swing.JButton tichstory;
    private javax.swing.JButton ticket_details;
    private javax.swing.JButton trip_details;
    // End of variables declaration//GEN-END:variables
}
